-- AlterEnum (safe — ADD VALUE IF NOT EXISTS)
ALTER TYPE "EscrowStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';

-- AlterTable (safe — ADD COLUMN IF NOT EXISTS)
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "releaseConfirmedAt" TIMESTAMP(3);
ALTER TABLE "Escrow" ADD COLUMN IF NOT EXISTS "releaseMode" TEXT NOT NULL DEFAULT 'AUTO';
