// ============================================================
// QUANTUM SIGNER SERVICE -- Falcon-512 Hybrid Signature Manager
// Singleton. Manages PQC key pairs and generates signatures
// for payloads before they reach DLT adapters.
//
// Hybrid Model:
//   - Falcon-512 = Identity & Data Integrity (Quantum-Resistant)
//   - ECDSA/EdDSA = Blockchain Transport Layer only
//
// TRIPLE-SIGNATURE PROTOCOL:
//   - sellerSig: Cryptographic proof of intent to sell/deliver
//   - buyerSig: Cryptographic proof of intent to buy/pay
//   - quantumSeal: Falcon-512 master seal validating the transaction
//   - shieldedTimestamp: Embedded within the Falcon-signed payload
// ============================================================

import { PostQuantumCrypto } from '../utils/PostQuantumCrypto';
import {
  TripleSignature,
  TripleSignInput,
  TripleSignPayload,
} from './multi-chain/types';

export interface PqcProof {
  /** Base64-encoded Falcon-512 detached signature */
  signature: string;
  /** Unix timestamp when the proof was generated */
  timestamp: number;
  /** Identifier of the entity being signed (asset, event, escrow) */
  entityId: string;
  /** Type of entity: 'ASSET' | 'EVENT' | 'ESCROW' | 'TRANSFER' */
  entityType: string;
}

export interface HybridSignature {
  /** Falcon-512 proof for off-chain verification */
  pqcProof: PqcProof;
  /** SHA3-512 hash of the original payload */
  payloadHash: string;
}

export class QuantumSignerService {
  private static instance: QuantumSignerService;

  private constructor() {}

  static getInstance(): QuantumSignerService {
    if (!QuantumSignerService.instance) {
      QuantumSignerService.instance = new QuantumSignerService();
    }
    return QuantumSignerService.instance;
  }

  /**
   * Generates a Falcon-512 hybrid signature for a payload.
   * @param payload Object to sign (will be JSON.stringify'd)
   * @param entityId Unique identifier of the entity
   * @param entityType Type of entity being signed
   * @param tenantSecretHex Tenant secret key (hex string, >= 4610 chars for production)
   * @returns HybridSignature containing PQC proof and payload hash
   */
  async signPayload(
    payload: object,
    entityId: string,
    entityType: string,
    tenantSecretHex: string
  ): Promise<HybridSignature> {
    const payloadString = JSON.stringify(payload);
    const payloadHash = this.computeHash(payloadString);

    const falconSignature = await PostQuantumCrypto.signPayloadFalcon512(
      payload,
      tenantSecretHex
    );

    const pqcProof: PqcProof = {
      signature: Buffer.from(falconSignature).toString('base64'),
      timestamp: Math.floor(Date.now() / 1000),
      entityId,
      entityType,
    };

    return {
      pqcProof,
      payloadHash,
    };
  }

  /**
   * Generates only the PQC proof string (Base64) for direct adapter injection.
   * Convenience method when adapters only need the raw proof.
   */
  async signPayloadRaw(
    payload: object,
    entityId: string,
    entityType: string,
    tenantSecretHex: string
  ): Promise<string> {
    const hybrid = await this.signPayload(payload, entityId, entityType, tenantSecretHex);
    return Buffer.from(JSON.stringify(hybrid.pqcProof)).toString('base64');
  }

  /**
   * Verifies a Falcon-512 signature against a payload.
   * NOTE: falcon-crypto does not expose verify in the current version.
   * This is a placeholder for when the library supports verification.
   */
  async verifySignature(
    _payload: object,
    _signatureBase64: string,
    _publicKeyHex: string
  ): Promise<boolean> {
    // falcon-crypto v1.0.6 does not export verifyDetached.
    // In production, integrate with oqs-node or liboqs bindings.
    // For now, we trust the signature was generated by our private key.
    return true;
  }

  // ============================================================
  // TRIPLE-SIGNATURE MULTI-SIG PROTOCOL
  // ============================================================

  /**
   * Generates a Triple-Signature payload for a transaction.
   * Combines Seller signature, Buyer signature, and Quantum Seal.
   *
   * @param input The transaction input data (seller, buyer, amount, etc.)
   * @param sellerSig Cryptographic proof from the seller (EdDSA/ECDSA)
   * @param buyerSig Cryptographic proof from the buyer (EdDSA/ECDSA)
   * @param quantumSecretHex Quantum Cert master secret for Falcon-512 seal
   * @returns TripleSignPayload with all signatures and validation status
   */
  async signTriple(
    input: TripleSignInput,
    sellerSig: string,
    buyerSig: string,
    quantumSecretHex: string
  ): Promise<TripleSignPayload> {
    // 1. Generate shielded timestamp (embedded in Falcon payload)
    const shieldedTimestamp = Math.floor(Date.now() / 1000);

    // 2. Build the aggregated payload for hashing
    const aggregatePayload = {
      sellerAddress: input.sellerAddress,
      buyerAddress: input.buyerAddress,
      amount: input.amount,
      assetAddress: input.assetAddress || null,
      txRef: input.txRef,
      sellerSig,
      buyerSig,
      shieldedTimestamp,
    };

    // 3. Compute SHA3-512 hash of the aggregated data
    const aggregatedHash = this.computeHash(JSON.stringify(aggregatePayload));

    // 4. Generate Quantum Seal (Falcon-512 signature over the aggregated hash)
    const falconSignature = await PostQuantumCrypto.signPayloadFalcon512(
      { aggregatedHash, shieldedTimestamp, txRef: input.txRef },
      quantumSecretHex
    );

    const quantumSeal = Buffer.from(falconSignature).toString('base64');

    // 5. Build the TripleSignature
    const signatures: TripleSignature = {
      sellerSig,
      buyerSig,
      quantumSeal,
      shieldedTimestamp,
      aggregatedHash,
    };

    // 6. Return the complete TripleSignPayload
    return {
      signatures,
      payload: input,
      quantumValidated: true,
      validatedAt: shieldedTimestamp,
    };
  }

  /**
   * Verifies a Triple-Signature payload.
   * Checks that all three signatures are present and the Quantum Seal
   * was generated by Quantum Cert.
   *
   * NOTE: Full Falcon verification requires liboqs integration.
   * This method validates structural integrity and presence.
   */
  async verifyTriple(
    triplePayload: TripleSignPayload
  ): Promise<{ valid: boolean; reason?: string }> {
    const { signatures, payload, quantumValidated } = triplePayload;

    // 1. Check presence of all signatures
    if (!signatures.sellerSig || signatures.sellerSig.length < 10) {
      return { valid: false, reason: 'Missing or invalid seller signature' };
    }
    if (!signatures.buyerSig || signatures.buyerSig.length < 10) {
      return { valid: false, reason: 'Missing or invalid buyer signature' };
    }
    if (!signatures.quantumSeal || signatures.quantumSeal.length < 10) {
      return { valid: false, reason: 'Missing or invalid quantum seal' };
    }

    // 2. Verify payload consistency
    if (!payload.sellerAddress || !payload.buyerAddress || !payload.amount) {
      return { valid: false, reason: 'Incomplete payload data' };
    }

    // 3. Verify Quantum Cert validation flag
    if (!quantumValidated) {
      return { valid: false, reason: 'Transaction not validated by Quantum Cert' };
    }

    // 4. Recompute aggregated hash to detect tampering
    const aggregatePayload = {
      sellerAddress: payload.sellerAddress,
      buyerAddress: payload.buyerAddress,
      amount: payload.amount,
      assetAddress: payload.assetAddress || null,
      txRef: payload.txRef,
      sellerSig: signatures.sellerSig,
      buyerSig: signatures.buyerSig,
      shieldedTimestamp: signatures.shieldedTimestamp,
    };
    const recomputedHash = this.computeHash(JSON.stringify(aggregatePayload));

    if (recomputedHash !== signatures.aggregatedHash) {
      return { valid: false, reason: 'Aggregated hash mismatch - payload tampered' };
    }

    // 5. Verify shielded timestamp is within reasonable range (5 min tolerance)
    const now = Math.floor(Date.now() / 1000);
    const timeDiff = Math.abs(now - signatures.shieldedTimestamp);
    if (timeDiff > 300) {
      return { valid: false, reason: 'Shielded timestamp expired or invalid' };
    }

    // NOTE: Full Falcon-512 cryptographic verification would require
    // liboqs or oqs-node integration. For now, we trust the seal
    // generated by our own service (similar to HSM trust model).

    return { valid: true };
  }

  private computeHash(data: string): string {
    const crypto = require('crypto');
    return crypto.createHash('sha3-512').update(data).digest('hex');
  }
}
